# Generated by Django 5.1.1 on 2024-09-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product name', max_length=40, unique=True)),
                ('short_description', models.CharField(default='Describe the product', max_length=100)),
                ('image', models.ImageField(upload_to='static/assets/images/drugs/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_orders_count', models.PositiveIntegerField(default=0)),
                ('total_count_on_warehouse', models.PositiveIntegerField(default=0)),
                ('sort_order', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
    ]
